Workaround fix for "hdiutil: create failed - Resource busy" error

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -134,6 +134,14 @@ jobs:
           ENCRYPTION_SECRET: ${{ secrets.ENCRYPTION_SECRET }}
           KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
 
+      # Workaround for "hdiutil: create failed - Resource busy" error
+      # https://github.com/actions/runner-images/issues/7522
+      - name: MacOS hdiutil workaround
+        run: |
+          echo killing...; sudo pkill -9 XProtect >/dev/null || true;
+          echo waiting...; while pgrep XProtect; do sleep 3; done;
+        if: runner.os == 'macOS'
+
       - name: Windows Prepare Codesign
         env:
           CODESIGN_CERT: ${{ secrets.CODESIGN_CERT}}
